https://towardsdatascience.com/residual-network-implementing-resnet-a7da63c7b278

https://github.com/FrancescoSaverioZuppichini/ResNet/blob/master/ResNet.ipynb

In [2]:
import torch
import torch.nn as nn

from functools import partial
from dataclasses import dataclass
from collections import OrderedDict

In [20]:
class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.in_channels, self.out_channels =  in_channels, out_channels
        self.blocks = nn.Identity()
        self.shortcut = nn.Identity()   
    
    def forward(self, x):
        print(x)
        residual = x
        print('residual', residual)
        if self.should_apply_shortcut: residual = self.shortcut(x)
        print('residual', residual)
        x = self.blocks(x)
        print("x", x)
        x += residual
        return x
    
    @property
    def should_apply_shortcut(self):
        print("----------")
        return self.in_channels != self.out_channels

In [21]:
ResidualBlock(32, 64)

ResidualBlock(
  (blocks): Identity()
  (shortcut): Identity()
)

In [23]:
dummy = torch.ones((1, 1, 1, 1))

print(dummy)
block = ResidualBlock(1, 64)
block(dummy)

tensor([[[[1.]]]])
tensor([[[[1.]]]])
residual tensor([[[[1.]]]])
----------
residual tensor([[[[1.]]]])
x tensor([[[[1.]]]])


tensor([[[[2.]]]])